## The data partition
defaults = [
        { path = ".*", mode=0, uid=0, gid=0, xattrs=[ ["",""]]},
    ]

[[img]]
name = "data.ext2"
version = "1.0.0"
image_type = "ext2"
fs_options = { blocks_count = 2048, log_block_size = 2, extra="", uuid="065bb6b6ab6111eba5c5001553d3df0d", journal=true }

[[img.dir]]
name = "/home"
mode = 0o777
uid = 0

[[img.dir]]
name = "/home/parsec"
mode = 0o700
uid = 1000

[[img.dir]]
name = "/home/parsec/tokens"
mode = 0o700
uid = 1000

[[img.dir]]
name = "/home/parsec/tokens/066ad977-3f4b-989f-7786-0d2d01b0ab67"
mode = 0o700
uid = 1000

## We use a softHSM on the emulator. The secrets are simply
## stored in this database.
## So these are not really secret!
[[img.file]]
name = "/home/parsec/tokens/066ad977-3f4b-989f-7786-0d2d01b0ab67/sqlite3.db"
source = "files/softhsm/tokens/066ad977-3f4b-989f-7786-0d2d01b0ab67/sqlite3.db"
mode = 0o600
uid = 1000
gid = 1000

[[img.dir]]
name = "/tmp"
mode = 0o755


