## The data partition
defaults = [
        { path = ".*", mode=0, uid=0, gid=0, xattrs=[ ["",""]]},
    ]

[[img]]
name = "data.ext2"
version = "1.0.0"
image_type = "ext2"
fs_options = { blocks_count = 2048, log_block_size = 2, extra="", uuid="065bb6b6ab6111eba5c5001553d3df0d", journal=true }

[[img.dir]]
name = "/tmp"
mode = 0o755


