defaults = [
        { path = ".*", mode=0o544 ,uid=0, gid=0, xattrs=[ ["",""]]},
    ]

[[img]]
name = "system.ext2"
version = "0.0.1"
image_type = "ext2"
fs_options = { blocks_count = 2048, log_block_size = 2, extra="", uuid="065bb6b6ab6111eba5c500155dd3df0d" }
include = ["base_files.toml"]

[[img.crate]]
name = "/sbin/parsec"
src_uri = {git = "https://github.com/parallaxsecond/parsec.git", rev="45a21bc7bd34b039b2bb8e3e045ea7ea058b7bfa"}
executables = [
        {source = "parsec", target = "/sbin/parsec"}
]
# Specify the executable when the filename is different from the source-name
executable = "parsec"
mode = 0o555
# SecureElement has uid/gid 1068
uid = 1068
gid = 1068
features = ["direct-authenticator","pkcs11-provider"]

[[img.crate]]
name = "/bin/ls"
src_uri = {git = "https://github.com/sabaton-rs/exa.git"}
executables = [
        {source = "exa", target = "/bin/ls"}
]
mode = 0o555
uid = 0
gid = 0

[[img.crate]]
name = "/sbin/vpncloud"
src_uri = { git = "https://github.com/dswd/vpncloud.git", rev= "16d5d47f01240e4f64896f64fa3f38115d4cc3d3"}
executables = [
        {source = "vpncloud", target = "/sbin/vpncloud"}
]
mode = 0o555

[[img.file]]
name = "/usr/bin/zsh"
source = "usr/bin/zsh"
mode = 0o555
uid = 0
gid = 0

### dropbear
#[[img.file]]
#name = "/etc/dropbear/dropbear_rsa_host_key"
#source = "secrets/dropbear_rsa_host_key"
#mode = 0o600

#[[img.file]]
#name = "/etc/dropbear/authorized_keys"
#source = "secrets/authorized_keys"
#mode = 0o600

[[img.file]]
name = "/usr/sbin/dropbear"
source = "usr/sbin/dropbear"
mode = 0o500
uid = 0
gid = 0

[[img.file]]
name = "/usr/sbin/dropbearmulti"
source = "usr/sbin/dropbearmulti"
mode = 0o500
uid = 0
gid = 0

[[img.link]]
name = "/usr/bin/scp"
source = "/usr/sbin/dropbearmulti"
mode = 0o555

[[img.link]]
name = "/usr/bin/ssh"
source = "/usr/sbin/dropbearmulti"
mode = 0o555

#### softhsm
[[img.file]]
name = "/usr/bin/softhsm2-util"
mode = 0o500
uid = 0
gid = 0

# Only secure element has access to this library
[[img.file]]
name = "/usr/lib/softhsm/libsofthsm2.so"
mode = 0o500
uid = 1068
gid = 1068

# Parsec configuration
#[[img.file]]
#name = "/etc/parsec_config.toml"
#source = "files/etc/parsec_config.toml"
#mode = 0o400
#uid = 1068
#gid = 1068

###### Utilities

[[img.crate]]
name = "/bin/bat"
src_uri = {git = "https://github.com/sharkdp/bat.git"}
executables = [
	{source = "bat", target = "/bin/bat"}
]
mode = 0o500
uid = 0
gid = 0
features = ["minimal-application"]

[[img.crate]]
name = "/bin/procs"
src_uri = {git = "https://github.com/dalance/procs.git"}
executables = [
	{source = "procs", target = "/bin/procs"}
]
mode = 0o500
uid = 0
gid = 0

[[img.crate]]
name = "/bin/kibi"
src_uri = {git = "https://github.com/ilai-deutel/kibi.git"}
executables = [
	{source = "kibi", target = "/bin/kibi"}
]
mode = 0o500
uid = 0
gid = 0


## Debug Applications

## Agetty
[[img.file]]
name = "/sbin/agetty"
strip = true

## System D Files

[[img.ifile]]
mode = 0o444
name = "/etc/systemd/system.conf"
source = """#
[Manager]
LogLevel=debug
""" 

[[img.file]]
name = "/lib/systemd/systemd"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/system-generators/systemd-getty-generator"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-journald"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-cgroups-agent"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-hibernate-resume"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-hostnamed"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-modules-load"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-networkd"
strip = true
mode = 0o555
uid = 996

[[img.file]]
name = "/lib/systemd/systemd-resolved"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-sysctl"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-logind"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/systemd-udevd"
strip = true
mode = 0o555

[[img.file]]
name = "/bin/networkctl"
strip = true
mode = 0o555

[[img.file]]
name = "/bin/systemctl"
strip = true
mode = 0o555

[[img.file]]
name = "/bin/journalctl"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/systemd/libsystemd-shared-248.so"
strip = true
mode = 0o555

[[img.file]]
name = "/lib/libsystemd.so.0.31.0"
mode = 0o555

[[img.link]]
name = "/lib/libsystemd.so.0"
source = "/lib/libsystemd.so.0.31.0"

[[img.link]]
name = "/lib/libsystemd.so"
source = "/lib/libsystemd.so.0.31.0"

[[img.link]]
name = "/sbin/init"
source = "/lib/systemd/systemd"



## Machine ID - leaving empty
[[img.ifile]]
name = "/etc/machine-id"
source = ""

### Startup files
[[img.file]]
name = "/lib/systemd/system/default.target"
source = "files/lib/systemd/system/default.target"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/debug-shell.service"
source = "files/lib/systemd/system/debug-shell.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/serial-getty@.service"
source = "files/lib/systemd/system/serial-getty@.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-journald.service"
source = "files/lib/systemd/system/systemd-journald.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-udevd.service"
source = "files/lib/systemd/system/systemd-udevd.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/multi-user.target"
source = "files/lib/systemd/system/multi-user.target"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/tmp.mount"
source = "files/lib/systemd/system/tmp.mount"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-journald.socket"
source = "files/lib/systemd/system/systemd-journald.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-networkd.socket"
source = "files/lib/systemd/system/systemd-networkd.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-networkd.service"
source = "files/lib/systemd/system/systemd-networkd.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-resolved.service"
#source = "files/lib/systemd/system/systemd-networkd.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/dbus.service"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/dbus.socket"
mode = 0o444

[[img.link]]
name = "/lib/systemd/system/sockets.target.wants/dbus.socket"
source = "../dbus.socket"

[[img.file]]
name = "/lib/systemd/system/sockets.target.wants/systemd-initctl.socket"
source = "files/lib/systemd/system/systemd-initctl.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/sockets.target.wants/systemd-journald-audit.socket"
source = "files/lib/systemd/system/systemd-journald-audit.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/sockets.target.wants/systemd-journald-dev-log.socket"
source = "files/lib/systemd/system/systemd-journald-dev-log.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/sockets.target.wants/systemd-journald.socket"
source = "files/lib/systemd/system/systemd-journald.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/sockets.target.wants/systemd-udevd-control.socket"
source = "files/lib/systemd/system/systemd-udevd-control.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/sockets.target.wants/systemd-udevd-kernel.socket"
source = "files/lib/systemd/system/systemd-udevd-kernel.socket"
mode = 0o444

[[img.file]]
name = "/lib/systemd/system/systemd-modules-load.service"
mode = 0o444

#### DEFAULT TARGETS ####
[[img.dir]]
name = "/lib/systemd/system/default.target.wants"

[[img.dir]]
name = "/lib/systemd/system/sysinit.target.wants"

[[img.link]]
name = "/lib/systemd/system/default.target.wants/systemd-networkd.service"
source = "../systemd-networkd.service"

[[img.link]]
name = "/lib/systemd/system/default.target.wants/dbus.service"
source = "../dbus.service"

[[img.link]]
name = "/lib/systemd/system/sysinit.target.wants/systemd-modules-load.service"
source = "../systemd-modules-load.service"

## SYSINIT target
[[img.ifile]]
name = "/lib/systemd/system/sysinit.target"
source = """##
[Unit]
Description=System Initialization
Conflicts=emergency.service emergency.target
#Wants=local-fs.target swap.target
#After=local-fs.target swap.target emergency.service emergency.target

"""


[[img.ifile]]
name = "/etc/nsswitch.conf"
mode = 0o444
source = """# /etc/nsswitch.conf
passwd:         files systemd
group:          files systemd
shadow:         files
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
"""


## DBUS Configuration ##
[[img.file]]
name = "/usr/share/dbus-1/system.conf"
source = "files/usr/share/dbus-1/system.conf"

[[img.file]]
name = "/usr/share/dbus-1/system-services/org.freedesktop.network1.service"
source = "files/usr/share/dbus-1/system-services/org.freedesktop.network1.service"

[[img.file]]
name = "/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service"
source = "files/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service"

[[img.file]]
name = "/usr/share/dbus-1/services/org.freedesktop.systemd1.service"
source = "files/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service"

[[img.file]]
name = "/bin/ifconfig"
source = "/bin/ifconfig.net-tools"
mode = 0o554


### NETWORK CONFIGURATION 

[[img.ifile]]
name = "/etc/systemd/network/20-eth0.network"
source = """##
[Match]
Name=eth0

[Link]
ActivationPolicy=always-up
RequiredForOnline=yes

[Network]
DHCP=ipv4
"""
mode = 0o444

[[img.ifile]]
name = "/etc/systemd/network/uplink.network"
source = """##
[Match]
Name=eth0

[Network]
Bridge=br0
"""
mode = 0o444

[[img.ifile]]
name = "/etc/systemd/network/br0.netdev"
source = """##
[NetDev]
Name=br0
Kind=bridge
"""
mode = 0o444

[[img.ifile]]
name = "/etc/systemd/network/br0.network"
source = """##
[Match]
Name=br0

[Network]
DNS=192.168.250.1
Address=192.168.250.33/24
Gateway=192.168.250.1
"""
mode = 0o444

[[img.link]]
name = "/lib/modules"
source = "/vendor/lib/modules"


## Module Load configuration
[[img.ifile]]
name = "/etc/modules-load.d/bridge-net.conf"
source = """# Load bridge driver at boot
ipv6
llc
stp
bridge
"""

## INSMOD

[[img.file]]
name = "/sbin/insmod"
source = "/sbin/insmod.kmod"
mode = 0o555


