## An image configuration file to craft a custom filesystem image
defaults = [
  {path = ".*", mode = 0o700, uid = 0, gid = 0, xattrs = []},
]

[[img]]
image_type = "cpio"
name = "initrd.cpio"
version = "1.0.0"

[[img.dir]]
name = "/dev"

[[img.dev]]
device_type = "c"
gid = 0
major = 5
minor = 1
mode = 0o700
name = "/dev/console"
uid = 0

# The kernel expects the initrd init to be at /init
[[img.crate]]
executables = [
  {source = "initrd", target = "/init"},
]
gid = 0
mode = 0o500
name = "/init"
src_uri = {git = "https://github.com/sabaton-rs/sabaton-initrd.git"}
uid = 0

[[img.dir]]
name = "/proc"

[[img.dir]]
name = "/sys"

[[img.dir]]
mode = 0x755
name = "/mnt"

[[img.dir]]
mode = 0x755
name = "/idex"

[[img.dir]]
mode = 0x755
name = "/mnt/system"

[[img.dir]]
name = "/etc"

[[img.ifile]]
name = "/etc/fstab"
source = '''# Fstab for initrd. 
#<dev>                          <mnt_point>     <type>  <mnt_flags options> <fs_mgr_flags>
# system partition must be mounted as root.
/dev/block/by-name/system           /           ext4    ro,noauto,nouser    slotselect,first_stage_mount,verity
/dev/block/by-name/vendor           /vendor     ext4    ro,noauto,nouser    slotselect,first_stage_mount,verity
/dev/block/by-name/data             /data       ext4    rw,noauto,nouser    first_stage_mount
'''

[[img.file]]
mode = 0o500
name = "/etc/veritykey.pub"
source = "secrets/verity/verity_rsa-2048-public-key.der"
