[general]
version = 1

[[segment]]
## members of the shmreader group can read shared memory
reader = "shmreader"
## members of the shmwriter group can write shared memory
writer = "shmwriter"

[[segment.mempool]]
size = 128
count = 10000

[[segment.mempool]]
size = 1024
count = 5000

[[segment.mempool]]
size = 16384
count = 1000

[[segment.mempool]]
size = 131072
count = 200

[[segment.mempool]]
size = 524288
count = 50

[[segment.mempool]]
size = 1048576
count = 30

[[segment.mempool]]
size = 4194304
count = 5